### ISSUE TITLE
How do I get applications belonging to a role?

### ISSUE THREAD

**Issue by kk2170** [onelogin/onelogin-ruby-sdk#12]
I would like to manage the role to which the application belongs using this library. 
So I need `get_role_apps` like ` get_user_apps`.
Do you happen to have such API?

**Comment by pitbulk** [comment]
The available API methods are described here:
https://developers.onelogin.com/api-docs/1/getting-started/dev-overview

There is nothing like get_role_apps right now

**Comment by kk2170** [comment]
Thank you for the Information.
I'll try to request in idea portal.
