### ISSUE TITLE
Query on Status?

### ISSUE THREAD

**Issue by clader** [onelogin/onelogin-ruby-sdk#17]
It seems we can retrieve and set the user status via this gem, however I am unable to send a query to filter users by a specific status.

Example, setting query params to:
```ruby
query_parameters = {
     status: 1,
     username: 'victor_*',
}
```
... yields an empty array.  When I just query for 'victor_*' I get over 40 users, half of which are active (status=1).  Not sure if this is a limitation of the API, but it would be extremely helpful in both the API and Gem.

**Comment by pitbulk** [comment]
Limitation of the API.
