### ISSUE TITLE
Confused about MFA

### ISSUE THREAD

**Issue by sardaukar** [onelogin/onelogin-ruby-sdk#32]
Hello!

I am able to create new users and set the password for them, but as I login I'm greeted with a message that I have to setup MFA. Is there a way to do this via the API too?

I've tried to create a session login token, but I get:

```
{
  "status": {
    "type": "bad request",
    "code": 400,
    "message": "MFA is required but the user has not set up any factors",
    "error": true
  }
}
```

And when I try to get the factors for my user's ID, I get an empty array:

```
auth_factors = client.get_factors(user.id)
=> []
```

Is there a way to set the policy for the user _a priori_, so I don't need MFA for users created via the API? What am I doing wrong?

Thanks for any help!

**Comment by pitbulk** [comment]
Only OneLogin SMS can be added with the API using [enroll_factor](https://github.com/onelogin/onelogin-ruby-sdk/blob/master/lib/onelogin/api/client.rb#L1480)
rest of MFA must be added manually by users on its profile.

See https://developers.onelogin.com/api-docs/1/multi-factor-authentication/enroll-factor

**Comment by sardaukar** [comment]
Thanks!
