### ISSUE TITLE
'limit' never seems to work as a query parameter

### ISSUE THREAD

**Issue by m0liere** [onelogin/onelogin-ruby-sdk#33]
I have tried using "limit" as a query parameter with get_users and get_events and it never seems to function properly
![screen shot 2019-02-19 at 12 46 19](https://user-images.githubusercontent.com/3681673/53035844-621d0400-3444-11e9-8981-0a4c06656a28.png)
![screen shot 2019-02-19 at 12 45 51](https://user-images.githubusercontent.com/3681673/53035845-621d0400-3444-11e9-86bf-e97d883b37e1.png)

**Comment by pitbulk** [comment]
Limit is used to limit how many result will be retrieved by API call (that parameter belong the OneLogin API).

If you want to limit the number of results, then use the max_results parameter.
