### ISSUE TITLE
Auth issues while iterating

### ISSUE THREAD

**Issue by hfcorreia** [onelogin/onelogin-ruby-sdk#35]
I have this rake task that generally works without any problem, yet it happens that 2 or 3 times a day I get a `OneLogin::Api::ApiException` while iterating over the OneLogin users which is a bit annoying.

This is the simple version of the code:
```
client = OneLogin::Api::Client.new(
      client_id: ENV.fetch('ONE_LOGIN_CLIENT_ID'),
      client_secret: ENV.fetch('ONE_LOGIN_CLIENT_SECRET'),
      region: ENV.fetch('ONE_LOGIN_REGION'))

client.get_users.each_with_object([]) { ... }
```

And this is part of the stack trace:
```
OneLogin::Api::ApiException: Authentication Failure
  from onelogin/api/cursor.rb:69:in `fetch_next_page'
  from onelogin/api/cursor.rb:47:in `each'
  from onelogin/api/cursor.rb:49:in `each'
  from onelogin/api/cursor.rb:49:in `each'
  from onelogin/api/cursor.rb:49:in `each'
  from onelogin/api/cursor.rb:49:in `each'
  from onelogin/api/cursor.rb:49:in `each'
  from onelogin/api/cursor.rb:49:in `each'
  from onelogin/api/cursor.rb:49:in `each'
  from onelogin/api/cursor.rb:49:in `each'
  from onelogin/api/cursor.rb:49:in `each'
  from onelogin/api/cursor.rb:49:in `each'
  from lib/my_file.rb:7:in `each_with_object'
```

It seems that there is some kind of issue when paginating the users, somehow occasionally it  loses the authorization to make the request and raises this exception. 

I also tried to see if it could be some kind of issue with rate limiting, but couldn't manage to get decent info to test this hypothesis out.

Any ideas of what this could be?

**Comment by pitbulk** [comment]
If the access_token expires or is invalidated, then OneLogin's platform will return a 401 rather than the expected response.

Can you try to improve the [fetch_next_page](https://github.com/onelogin/onelogin-ruby-sdk/blob/master/lib/onelogin/api/cursor.rb#L55) method

Can you apply the patch suggested at https://github.com/onelogin/onelogin-ruby-sdk/pull/34 and verify that this solves your case?
