### ISSUE TITLE
Endpoints v2

### ISSUE THREAD

**Issue by RajatPawar** [onelogin/onelogin-ruby-sdk#48]
First of all, thanks for the gem, it makes life easier :)
Secondly, the README says 'This SDK will let you execute all the API methods, version/1', but I see that a lot of endpoints on the OneLogin API reference have an equivalent version/2 now. Are there any plans of supporting that in this gem?

**Comment by pitbulk** [comment]
Yes, we plan to support it soon, we are still figuring out best strategy to support the different endpoints/objects and make them compatible and with the right UX.

**Comment by RajatPawar** [comment]
Appreciate it, thanks a lot!
